/** Language metadata: translation code, TTS locale, map center, and region label. */
const LANGUAGES = [
  {
    code: "es",
    name: "Spanish",
    speechLang: "es-ES",
    country: "Spain",
    lat: 40.4168,
    lng: -3.7038,
    zoom: 5,
  },
  {
    code: "fr",
    name: "French",
    speechLang: "fr-FR",
    country: "France",
    lat: 48.8566,
    lng: 2.3522,
    zoom: 5,
  },
  {
    code: "de",
    name: "German",
    speechLang: "de-DE",
    country: "Germany",
    lat: 52.52,
    lng: 13.405,
    zoom: 5,
  },
  {
    code: "it",
    name: "Italian",
    speechLang: "it-IT",
    country: "Italy",
    lat: 41.9028,
    lng: 12.4964,
    zoom: 5,
  },
  {
    code: "pt",
    name: "Portuguese",
    speechLang: "pt-PT",
    country: "Portugal",
    lat: 38.7223,
    lng: -9.1393,
    zoom: 5,
  },
  {
    code: "nl",
    name: "Dutch",
    speechLang: "nl-NL",
    country: "Netherlands",
    lat: 52.3676,
    lng: 4.9041,
    zoom: 6,
  },
  {
    code: "pl",
    name: "Polish",
    speechLang: "pl-PL",
    country: "Poland",
    lat: 52.2297,
    lng: 21.0122,
    zoom: 5,
  },
  {
    code: "ru",
    name: "Russian",
    speechLang: "ru-RU",
    country: "Russia",
    lat: 55.7558,
    lng: 37.6173,
    zoom: 4,
  },
  {
    code: "ja",
    name: "Japanese",
    speechLang: "ja-JP",
    country: "Japan",
    lat: 35.6762,
    lng: 139.6503,
    zoom: 5,
  },
  {
    code: "ko",
    name: "Korean",
    speechLang: "ko-KR",
    country: "South Korea",
    lat: 37.5665,
    lng: 126.978,
    zoom: 6,
  },
  {
    code: "zh",
    name: "Chinese (Simplified)",
    speechLang: "zh-CN",
    country: "China",
    lat: 39.9042,
    lng: 116.4074,
    zoom: 4,
  },
  {
    code: "ar",
    name: "Arabic",
    speechLang: "ar-SA",
    country: "Saudi Arabia",
    lat: 24.7136,
    lng: 46.6753,
    zoom: 5,
  },
  {
    code: "hi",
    name: "Hindi",
    speechLang: "hi-IN",
    country: "India",
    lat: 28.6139,
    lng: 77.209,
    zoom: 4,
  },
  {
    code: "tr",
    name: "Turkish",
    speechLang: "tr-TR",
    country: "Turkey",
    lat: 41.0082,
    lng: 28.9784,
    zoom: 5,
  },
  {
    code: "sv",
    name: "Swedish",
    speechLang: "sv-SE",
    country: "Sweden",
    lat: 59.3293,
    lng: 18.0686,
    zoom: 5,
  },
  {
    code: "el",
    name: "Greek",
    speechLang: "el-GR",
    country: "Greece",
    lat: 37.9838,
    lng: 23.7275,
    zoom: 6,
  },
  {
    code: "he",
    name: "Hebrew",
    speechLang: "he-IL",
    country: "Israel",
    lat: 32.0853,
    lng: 34.7818,
    zoom: 6,
  },
  {
    code: "th",
    name: "Thai",
    speechLang: "th-TH",
    country: "Thailand",
    lat: 13.7563,
    lng: 100.5018,
    zoom: 5,
  },
  {
    code: "vi",
    name: "Vietnamese",
    speechLang: "vi-VN",
    country: "Vietnam",
    lat: 21.0285,
    lng: 105.8542,
    zoom: 5,
  },
  {
    code: "id",
    name: "Indonesian",
    speechLang: "id-ID",
    country: "Indonesia",
    lat: -6.2088,
    lng: 106.8456,
    zoom: 4,
  },
];

function getLanguageByCode(code) {
  return LANGUAGES.find((lang) => lang.code === code) ?? LANGUAGES[0];
}
